trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'AzureDemoSubscription'
    ScriptType: 'FilePath'
    ScriptPath: './Deploy-AzTemplate2.ps1'
    azurePowerShellVersion: 'LatestVersion'