trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: '4a0f819a-3afb-4efd-af36-0034da0866a2'
    ScriptType: 'FilePath'
    ScriptPath: './Deploy-AzTemplate.ps1'
    ScriptArguments: -Location 'centralus' -ResourceGroupName 'demogroup' -TemplateFile AppServiceARM.json
    azurePowerShellVersion: 'LatestVersion'